<a href="https://colab.research.google.com/github/Ghule-vaibhavi/-machine-learning-model/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import kagglehub
import pandas as pd
import os
import glob

# Download dataset
path = kagglehub.dataset_download(
    "akalyasubramanian/dataset-for-knn-classification"
)

print("Dataset path:", path)

# Find CSV files
csv_files = glob.glob(
    os.path.join(path, "**", "*.csv"),
    recursive=True
)

print("CSV files:", csv_files)

# Load the first CSV file
if not csv_files:
    raise FileNotFoundError("No CSV file found in the dataset.")

df = pd.read_csv(csv_files[0])

Using Colab cache for faster access to the 'dataset-for-knn-classification' dataset.
Dataset path: /kaggle/input/dataset-for-knn-classification
CSV files: ['/kaggle/input/dataset-for-knn-classification/TShirt_size.csv']

In [3]:
# Inspect dataset
print("\nFirst 5 rows:")
display(df.head())

First 5 rows:

   Height (in cms)  Weight (in kgs) T Shirt Size
0              158               58            M
1              158               59            M
2              158               63            M
3              160               59            M
4              160               60            M

In [4]:
print("\nDataset shape:", df.shape)
print("\nColumn names:", df.columns.tolist())
print("\nData types:")
print(df.dtypes)

Dataset shape: (18, 3)

Column names: ['Height (in cms)', 'Weight (in kgs)', 'T Shirt Size']

Data types:
Height (in cms)     int64
Weight (in kgs)     int64
T Shirt Size       object
dtype: object

In [5]:

print("\nMissing values:")
print(df.isnull().sum())

Missing values:
Height (in cms)    0
Weight (in kgs)    0
T Shirt Size       0
dtype: int64

In [6]:


print("\nUnique values in each column:")
print(df.nunique())

Unique values in each column:
Height (in cms)     6
Weight (in kgs)    10
T Shirt Size        2
dtype: int64

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load your existing dataset
# df is already loaded from your Kaggle dataset

# Select input and target columns
X = df[['Height (in cms)', 'Weight (in kgs)']]
y = df['T Shirt Size']

# Check missing values
print("Missing values:\n", df.isnull().sum())

# Remove rows containing missing values
data = df.dropna(subset=[
    'Height (in cms)',
    'Weight (in kgs)',
    'T Shirt Size'
])

X = data[['Height (in cms)', 'Weight (in kgs)']]
y = data['T Shirt Size']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Create KNN pipeline
model = Pipeline([
    ('scaler', StandardScaler()),
    ('knn', KNeighborsClassifier(n_neighbors=5))
])

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred, zero_division=0))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

Missing values:
 Height (in cms)    0
Weight (in kgs)    0
T Shirt Size       0
dtype: int64
Accuracy: 1.0

Classification Report:

              precision    recall  f1-score   support

           L       1.00      1.00      1.00         2
           M       1.00      1.00      1.00         2

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4


Confusion Matrix:

[[2 0]
 [0 2]]

In [10]:
new_person = pd.DataFrame({
    'Height (in cms)': [170],
    'Weight (in kgs)': [65]
})

prediction = model.predict(new_person)

print("Predicted T-shirt size:", prediction[0])

Predicted T-shirt size: L

In [8]:
print(df.columns.tolist())
display(df.head())

['Height (in cms)', 'Weight (in kgs)', 'T Shirt Size']

   Height (in cms)  Weight (in kgs) T Shirt Size
0              158               58            M
1              158               59            M
2              158               63            M
3              160               59            M
4              160               60            M