<a href="https://colab.research.google.com/github/Ghule-vaibhavi/-machine-learning-model/blob/main/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

linear regression algorithm ,house price prediction

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import kagglehub
import os
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [ ]:
path = kagglehub.dataset_download("debayank2024/house-price-prediction")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/debayank2024/house-price-prediction/1.archive...

100%|██████████| 145k/145k [00:00<00:00, 60.3MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/debayank2024/house-price-prediction/versions/1

In [ ]:
for root,dirs,files in os.walk(path):
    for file in files:
        print(file)

modified_data.csv

In [ ]:
csv_file = os.path.join(path,"modified_data.csv")
df = pd.read_csv(csv_file)
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,price_per_sqft
0,2014-05-02,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,233.58
1,2014-05-02,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,653.15
2,2014-05-02,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,177.20
3,2014-05-02,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,210.00
4,2014-05-02,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,283.51

In [ ]:
df.shape

(4600, 18)

In [ ]:
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'price_per_sqft'],
      dtype='object')

In [ ]:
df.isnull().sum()

date              0
price             0
bedrooms          0
bathrooms         0
sqft_living       0
sqft_lot          0
floors            0
waterfront        0
view              0
condition         0
sqft_above        0
sqft_basement     0
yr_built          0
yr_renovated      0
street            0
city              0
statezip          0
price_per_sqft    0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            4600 non-null   object
 1   price           4600 non-null   float64
 2   bedrooms        4600 non-null   float64
 3   bathrooms       4600 non-null   float64
 4   sqft_living     4600 non-null   int64
 5   sqft_lot        4600 non-null   int64
 6   floors          4600 non-null   float64
 7   waterfront      4600 non-null   int64
 8   view            4600 non-null   int64
 9   condition       4600 non-null   int64
 10  sqft_above      4600 non-null   int64
 11  sqft_basement   4600 non-null   int64
 12  yr_built        4600 non-null   int64
 13  yr_renovated    4600 non-null   int64
 14  street          4600 non-null   object
 15  city            4600 non-null   object
 16  statezip        4600 non-null   object
 17  price_per_sqft  4600 non-null   float64
dtypes: float64(5), int64(9), object(4)
memory usage: 647.0+ KB

In [ ]:
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,price_per_sqft
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261,265.876209
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536,357.503362
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000,180.817500
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000,243.855000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000,314.840000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000,22533.900000

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop(columns=["date","price_per_sqft"],inplace=True,)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          4600 non-null   float64
 1   bedrooms       4600 non-null   float64
 2   bathrooms      4600 non-null   float64
 3   sqft_living    4600 non-null   int64
 4   sqft_lot       4600 non-null   int64
 5   floors         4600 non-null   float64
 6   waterfront     4600 non-null   int64
 7   view           4600 non-null   int64
 8   condition      4600 non-null   int64
 9   sqft_above     4600 non-null   int64
 10  sqft_basement  4600 non-null   int64
 11  yr_built       4600 non-null   int64
 12  yr_renovated   4600 non-null   int64
 13  street         4600 non-null   object
 14  city           4600 non-null   object
 15  statezip       4600 non-null   object
dtypes: float64(4), int64(9), object(3)
memory usage: 575.1+ KB

In [ ]:
df = df[df['price'] < df['price'].quantile(0.90)]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4133 entries, 0 to 4599
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          4133 non-null   float64
 1   bedrooms       4133 non-null   float64
 2   bathrooms      4133 non-null   float64
 3   sqft_living    4133 non-null   int64
 4   sqft_lot       4133 non-null   int64
 5   floors         4133 non-null   float64
 6   waterfront     4133 non-null   int64
 7   view           4133 non-null   int64
 8   condition      4133 non-null   int64
 9   sqft_above     4133 non-null   int64
 10  sqft_basement  4133 non-null   int64
 11  yr_built       4133 non-null   int64
 12  yr_renovated   4133 non-null   int64
 13  street         4133 non-null   object
 14  city           4133 non-null   object
 15  statezip       4133 non-null   object
dtypes: float64(4), int64(9), object(3)
memory usage: 548.9+ KB

In [ ]:
df = df.drop_duplicates()

# Keep only the strongest real features for price prediction.
# Remove target-derived and weak columns.
X = df.drop(columns=['price'],axis=1)

y = df['price']

# Convert only categorical feature columns; keep price as numeric target.
X = pd.get_dummies(X,drop_first=True)
print(y.head())

0    313000.0
2    342000.0
3    420000.0
4    550000.0
5    490000.0
Name: price, dtype: float64

In [ ]:
print(X.head())

   bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0       3.0       1.50         1340      7912     1.5           0     0
2       3.0       2.00         1930     11947     1.0           0     0
3       3.0       2.25         2000      8030     1.0           0     0
4       4.0       2.50         1940     10500     1.0           0     0
5       2.0       1.00          880      6380     1.0           0     0

   condition  sqft_above  sqft_basement  ...  statezip_WA 98155  \
0          3        1340              0  ...              False
2          4        1930              0  ...              False
3          4        1000           1000  ...              False
4          4        1140            800  ...              False
5          3         880              0  ...              False

   statezip_WA 98166  statezip_WA 98168  statezip_WA 98177  statezip_WA 98178  \
0              False              False              False              False
2              False              False              False              False
3              False              False              False              False
4              False              False              False              False
5              False              False              False              False

   statezip_WA 98188  statezip_WA 98198  statezip_WA 98199  statezip_WA 98288  \
0              False              False              False              False
2              False              False              False              False
3              False              False              False              False
4              False              False              False              False
5              False              False              False              False

   statezip_WA 98354
0              False
2              False
3              False
4              False
5              False

[5 rows x 4195 columns]

In [ ]:
print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (4133, 4195)
Target shape: (4133,)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4133 entries, 0 to 4599
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          4133 non-null   float64
 1   bedrooms       4133 non-null   float64
 2   bathrooms      4133 non-null   float64
 3   sqft_living    4133 non-null   int64
 4   sqft_lot       4133 non-null   int64
 5   floors         4133 non-null   float64
 6   waterfront     4133 non-null   int64
 7   view           4133 non-null   int64
 8   condition      4133 non-null   int64
 9   sqft_above     4133 non-null   int64
 10  sqft_basement  4133 non-null   int64
 11  yr_built       4133 non-null   int64
 12  yr_renovated   4133 non-null   int64
 13  street         4133 non-null   object
 14  city           4133 non-null   object
 15  statezip       4133 non-null   object
dtypes: float64(4), int64(9), object(3)
memory usage: 548.9+ KB

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
print("\nTrain Data")
print(x_train.shape,y_train.shape)
print("\nTest Data")
print(x_test.shape,y_test.shape)

Train Data
(3306, 4195) (3306,)

Test Data
(827, 4195) (827,)

In [ ]:
scaler = StandardScaler()
x_train_scaler = scaler.fit_transform(x_train)
x_test_scaler = scaler.transform(x_test)

In [ ]:
lr = LinearRegression()
model_lr = lr.fit(x_train_scaler,y_train)
y_pred_lr = model_lr.predict(x_test_scaler)

score_lr = r2_score(y_test,y_pred_lr)*100
mae_lr = mean_absolute_error(y_test,y_pred_lr)
mse_lr = mean_squared_error(y_test,y_pred_lr)
rmse_lr = root_mean_squared_error(y_test,y_pred_lr)

print('\nLinear Regression')
print("\nR2 Score")
print(score_lr)
print("\nMean Absolute Error")
print(mae_lr)
print("\nMean Square Error")
print(mse_lr)
print("\nRoot Mean Square Error")
print(rmse_lr)

Linear Regression

R2 Score
47.9809831187176

Mean Absolute Error
88408.11338043922

Mean Square Error
18276834397.692917

Root Mean Square Error
135191.8429406631

In [ ]:

loss = mean_squared_error(y_test, y_pred_lr)
print("Loss (MSE):", loss)

Loss (MSE): 18276834397.692917